<a href="https://colab.research.google.com/github/MUSSAFARA-RIAZ/ds-learning-log/blob/main/Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Imbalanced Dataset**
A dataset with an unequal class distribution

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/credit_data.csv')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [3]:
df.shape

(29799, 31)

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [16]:

df.fillna(0, inplace=True)  # or use a different value/method

#distribution of two classes
df['Class'].value_counts()

Class
0.0    29705
1.0       94
Name: count, dtype: int64

This is highly imbalanced dataset
0- Legit
1- Fradulent

In [18]:
df['Class'] = df['Class'].astype(int)
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [21]:
legit=df[df.Class==0]
fraud=df[df.Class==1]
print(legit.shape)
print(fraud.shape)

(29705, 31)
(94, 31)

Undersampling

---
Undersampling means reducing the number of examples in the majority class so it matches (or is closer to) the number of examples in the minority class.

In [22]:
# build a sample dataset containing the same distribution of legit and fraud transaction

In [23]:
legit_sample=legit.sample(n=94)

In [24]:
legit_sample.shape

(94, 31)

In [25]:
#Concatenate the dataframe

In [26]:
new_df=pd.concat([legit_sample,fraud],axis=0)
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
20158,30828,-0.533862,0.663487,1.957097,1.230102,0.077126,0.079218,0.219042,0.235731,-0.081152,...,-0.156506,-0.336309,-0.074883,0.038587,-0.155905,-0.389740,0.154826,0.119809,1.00,0
10338,16482,1.283515,0.343553,-0.181519,1.018967,0.461474,-0.106028,0.144344,-0.237342,1.347136,...,-0.194476,-0.327551,-0.289710,-1.061519,0.842216,-0.283936,-0.020396,0.005568,36.71,0
7874,10948,-1.106141,0.501163,2.648647,-0.466568,0.091303,-0.445360,0.600087,-0.577732,1.113341,...,-0.031815,0.448026,-0.169950,0.568905,0.060785,0.944826,-0.797170,-0.297027,14.95,0
12469,21860,1.243466,0.263469,0.283228,1.251431,0.384538,0.705842,-0.201194,0.003737,1.449929,...,-0.232542,-0.143027,-0.307755,-1.036275,0.907642,-0.247481,0.013325,-0.005313,9.99,0
24651,33314,1.317910,-1.101923,-0.663724,-1.761183,0.965597,3.552032,-1.522825,0.914951,-0.550148,...,0.364383,0.728963,-0.190160,1.052204,0.568320,-0.040541,0.029502,0.029389,69.99,0

In [27]:
new_df['Class'].value_counts()

Class
0    94
1    94
Name: count, dtype: int64